### ISSUE TITLE
Get imdb id of show?

### ISSUE THREAD

**Issue by ibrahimmumcu** [Alvaroctal/TMDB-PHP-API#3]
<?php
$idTVShow = $_GET['id'];
$tvShow = $tmdb->getTVShow($idTVShow);
print_r($tvShow);
?>

This code doesn't give me imdb id of show. How can I get it?

**Comment by CaptainBarnius** [comment]
You have different ways to get the imdb id of a show. With your code:
<?php
$idTVShow = $_GET['id'];

//Add the external_ids to the response or modify the function getTvShow
$tvShow = $tmdb->getTVShow($idTVShow, 'append_to_response=external_ids');

//Now your object has an array with external_ids
$external_ids = $tvShow->get('external_ids');

//print_r($external_ids);	
echo $external_ids['imdb_id'];
	
echo'<pre>';
print_r($tvShow);
echo '</pre>';

**Comment by Alvaroctal** [comment]
now, a more polite way would be:
`$tvShow = $tmdb->getTVShow($idTVShow, array('external_ids'));`
anyway, previous is also valid.
