### ISSUE TITLE
About Casting

### ISSUE THREAD

**Issue by akshar001** [Alvaroctal/TMDB-PHP-API#6]
Its not an issue but i am using your api for my college project work and thank you guys for creating it..,
Can you just tell me how to get casting of a movie..
it would be very helpful.

**Comment by SpiderBro** [comment]
You could try:

`$tmdb->getMovie($id, 'append_to_response=credits');`

**Comment by Alvaroctal** [comment]
Fixed, now, by default the library will provide the credits.

**Comment by akshar001** [comment]
Thanks  what you are doing is great..
