### ISSUE TITLE
how to get genres 

### ISSUE THREAD

**Issue by kama-tech** [Alvaroctal/TMDB-PHP-API#8]
hi all , very helpfull api , but somebody know how to get genres from movies.

I try 
$movie = $tmdb->getMovie(11);
$id = $movie->getID();
echo $movie->get($id, 'genres') .;
--------------------------------------
$id = $movie->getID();
echo . $movie->get($id, 'append_to_response=genres') .;

without luck. any help thanks.

**Comment by Alvaroctal** [comment]
Ok, now its a bit easier:
$movie->getGenres();

ps: sorry for the delay.
