### ISSUE TITLE
Error in getImageURL()

### ISSUE THREAD

**Issue by wunderkinnd** [Alvaroctal/TMDB-PHP-API#9]
Great job. But I found a bug:

$tmdb->getImageURL()
doesn't work, I think. I get no URL back.

Is there a possibility to get ALL posters according to a movie?

Thanks a lot

**Comment by Alvaroctal** [comment]
Maybe you forgot to init tmdb with your API key: https://github.com/Alvaroctal/TMDB-PHP-API/blob/master/examples/index.php#L125

once you have it, its pretty easy: https://github.com/Alvaroctal/TMDB-PHP-API/blob/master/examples/movies/infoMovie.php#L13
